### ISSUE TITLE
Так не хранят настройки

### ISSUE THREAD

**Issue by DmitriyRudenskiy** [ZolotukhinVM/project02.loftschool#1]
class Config
{
    const DB_HOST = '';
    const DB_NAME = '';
    const DB_USER = '';
    const DB_PASSWORD = '';
    const SHOW_ERRORS = true;
}
Во первых константы хранят в интерфейсе, во вторых администраторы которые знают пароли не знают классы php

**Comment by ZolotukhinVM** [comment]
исправлено.
