### ISSUE TITLE
Для каких целей переменная $db ?

### ISSUE THREAD

**Issue by DmitriyRudenskiy** [ZolotukhinVM/project02.loftschool#2]
$db = static::getDB();
        $sql = "SELECT `id`, `password` FROM `users_tbl` 
                            WHERE `login` = '" . $arrPost['login'] . "'";
        $stmt = $db->query($sql);
можно написать так 
        $sql = "SELECT `id`, `password` FROM `users_tbl` 
                            WHERE `login` = '" . $arrPost['login'] . "'";
        $stmt = $this->getDB()->query($sql);

**Comment by ZolotukhinVM** [comment]
self::getDB()*
Исправлено.
