### ISSUE TITLE
Уезвимость в коде

### ISSUE THREAD

**Issue by DmitriyRudenskiy** [ZolotukhinVM/project02.loftschool#3]
INSERT INTO `users_tbl`(login, password, name, age, comment, photo) 
                    VALUES('$login', '$password', '" . $_POST["name"] . "', '" . $_POST["age"] . "', '" . $_POST["comment"] . "', '" . $_FILES["userfile"]["name"] . "')

Читаем, учим, используем!
https://secure.php.net/manual/ru/pdostatement.bindvalue.php

**Comment by ZolotukhinVM** [comment]
Исправлено.
